[package]
name = "kaji-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
kaji = { path = "../kaji" }
kaji-rules = { path = "../kaji-rules" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
