[package]
name = "kaji-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
kaji = { path = "../kaji" }
kaji-rules = { path = "../kaji-rules" }
kaji-loader = { path = "../kaji-loader" }

[dev-dependencies]
rstest = "0.25.0"
